// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5p_Qy8f14VwwhHR8BaTgLOqj458pwwhM',
    appId: '1:1067447046986:web:f06a7144282b1aa2b867b3',
    messagingSenderId: '1067447046986',
    projectId: 'zamalek-chat-9ecc3',
    authDomain: 'zamalek-chat-9ecc3.firebaseapp.com',
    storageBucket: 'zamalek-chat-9ecc3.appspot.com',
    measurementId: 'G-PP1GN4Z8NZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHe3IJWYut6tzvKpO7PP7ajiySaTMR0BM',
    appId: '1:1067447046986:android:38553b1731b40273b867b3',
    messagingSenderId: '1067447046986',
    projectId: 'zamalek-chat-9ecc3',
    storageBucket: 'zamalek-chat-9ecc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC80vGMoT5dlkwyyeUSIJwHuDnfFLZT0QA',
    appId: '1:1067447046986:ios:462c4bcaa2c04ffcb867b3',
    messagingSenderId: '1067447046986',
    projectId: 'zamalek-chat-9ecc3',
    storageBucket: 'zamalek-chat-9ecc3.appspot.com',
    iosClientId: '1067447046986-nid79ihrkpmd6pkget8pvv8sekst6qrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC80vGMoT5dlkwyyeUSIJwHuDnfFLZT0QA',
    appId: '1:1067447046986:ios:462c4bcaa2c04ffcb867b3',
    messagingSenderId: '1067447046986',
    projectId: 'zamalek-chat-9ecc3',
    storageBucket: 'zamalek-chat-9ecc3.appspot.com',
    iosClientId: '1067447046986-nid79ihrkpmd6pkget8pvv8sekst6qrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
